### ISSUE TITLE
infolabel7 is missing in glade file

### ISSUE THREAD

**Issue by superkartoffel** [gambitcomminc/mqtt-stats#4]
Hi, thanks for publishing this tool.
unfortunately I could not get it to run. When I start your example:
`./mqtt-stats.py --host mqtt.eclipse.org --topic '#' --qos 2`

I get a error message:

```
WARNING 2021-04-27 10:01:56,092 (mqtt-stats.py-409) - no CSS file /mnt/c/Users/hvorwerk/source/repos/mqtt-stats/mqtt-stats.css, ignoring...
Traceback (most recent call last):
  File "./mqtt-stats.py", line 743, in <module>
    main.start()
  File "./mqtt-stats.py", line 336, in start
    self.show_gui()
  File "./mqtt-stats.py", line 472, in show_gui
    self.infolabel7.set_text("")
AttributeError: 'NoneType' object has no attribute 'set_text'
```

Looks like infolabel7 is not in mqtt-stats.glade

**Comment by gambitcomminc** [comment]
Fixed.
